name: Simple Asset Size Reporter

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2-beta
      with:
        fetch-depth: 0
    - uses: chrysanthos/simple-asset-size-reporter@1.0.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        files: '["assets/js/**/*.js", "assets/css/**/*.css"]'
        with-same: 'false'
        build-assets: 'false'
